= Git for technical writers
:toc: left
:icons: font
:numbered:
:source-highlighter: highlightjs

== Overview
Are you new to doc-as-code concept and you don't know where to start?

Then you're at the right place. I've designed this course for specifically for technical writers. This course contains everything that a technical writer should know about Git, GitLab and GitHub.

== What's Git?

Git is a version control system. Git keeps track of the changes you make to files, so you have a record of what you and your peers have done and may roll back to specific versions if necessary. For more information, review my link:https://beingtechnicalwriter.com/gittechnicalwriters/[blog].

== How this course is designed?

There are no prerequisites for this course. All you need is a system and interest to learn Git. In this course we will cover:

* link:git/index{outfilesuffix}[Getting started with Git]
* link:git/install_run{outfilesuffix}[Install and run Git quickstart]
* link:gitlab/index{outfilesuffix}[Getting started with GitLab]
* link:gitlab/install_run{outfilesuffix}[Install and run GitLab quickstart]
* link:github/index{outfilesuffix}[Getting started with GitHub]
* link:github/install_run{outfilesuffix}[Install and run GitHub quickstart]
* link:resources/index{outfilesuffix}[Important Resources]
* link:upnext/index{outfilesuffix}[What's Next]

== Get support

To get support you can:

* Drop a mail to me - link:mailto:trivedi.gaurav30@gmail.com[Gaurav's email].